#!/usr/bin/env node
// bootstrap.mjs — cross-platform installer (Windows, macOS, Linux). Node is the one
// runtime claude-kit already requires (the hooks are Node), so the installer is Node too
// — no bash/symlink assumptions (KIT-T011). bootstrap.sh is now a thin POSIX wrapper.
//
// Installs ONLY what a plugin can't reach (KIT-D013): the composed ~/.claude/CLAUDE.md
// (public base + private overlay), the PRIVATE overlay's own tooling, and the statusline.
// The PLUGIN owns the public tooling. LINK_TOOLING=1 restores the legacy full symlink
// install for machines that do NOT use the plugin.
//
//   node bootstrap.mjs                 # overlay mode: CLAUDE.md + private overlay + statusline
//   LINK_TOOLING=1 node bootstrap.mjs  # ALSO symlink the public tooling (non-plugin install)
//   DRY_RUN=1 node bootstrap.mjs       # print what it would do, change nothing

import {
  existsSync, mkdirSync, readdirSync, renameSync, rmSync, symlinkSync, lstatSync,
  copyFileSync, readFileSync, writeFileSync, chmodSync,
} from 'node:fs';
import { join, dirname } from 'node:path';
import { homedir } from 'node:os';
import { fileURLToPath } from 'node:url';

const KIT = dirname(fileURLToPath(import.meta.url));
const CLAUDE = process.env.CLAUDE_HOME || join(homedir(), '.claude');
const DRY_RUN = process.env.DRY_RUN === '1';
const LINK_TOOLING = process.env.LINK_TOOLING === '1';

for (const d of ['commands', 'agents', 'skills', 'hooks']) mkdirSync(join(CLAUDE, d), { recursive: true });

// Back up a real (non-symlink) file/dir before it's replaced by a link or generated file.
function backup(dst) {
  let st;
  try { st = lstatSync(dst); } catch { return; }
  if (st.isSymbolicLink()) { rmSync(dst, { force: true }); return; } // stale link: just drop it
  const bak = `${dst}.bak.${Date.now()}`;
  renameSync(dst, bak);
  console.log(`  backed up existing ${dst} -> ${bak}`);
}

// Link src -> dst. Directories use a junction (works on Windows with no privilege; the
// type arg is ignored on POSIX). File links fall back to a copy where the OS forbids a
// symlink (Windows without the symlink privilege), so the install never hard-fails.
function link(src, dst, type) {
  if (DRY_RUN) { console.log(`  [dry-run] ${dst} -> ${src}`); return; }
  backup(dst);
  try {
    symlinkSync(src, dst, type);
    console.log(`  linked ${dst}`);
  } catch (e) {
    if (type === 'file') {
      copyFileSync(src, dst);
      console.log(`  copied ${dst} (symlink unavailable: ${e.code})`);
    } else {
      throw e;
    }
  }
}

// kind: md | md-noreadme | dirs | mjs — link a layer's items; no-op if the dir is absent.
function linkItems(src, dst, kind) {
  if (!existsSync(src)) return;
  mkdirSync(dst, { recursive: true });
  for (const e of readdirSync(src, { withFileTypes: true })) {
    if (kind === 'dirs') {
      if (e.isDirectory()) link(join(src, e.name), join(dst, e.name), 'junction');
    } else if (kind === 'mjs') {
      if (e.isFile() && e.name.endsWith('.mjs')) link(join(src, e.name), join(dst, e.name), 'file');
    } else if (e.isFile() && e.name.endsWith('.md')) {
      if (kind === 'md-noreadme' && e.name === 'README.md') continue;
      link(join(src, e.name), join(dst, e.name), 'file');
    }
  }
}

// Compose ~/.claude/CLAUDE.md from an optional public base + optional overlay. Dormant
// until at least one source exists, so it never clobbers a hand-maintained global file.
function composeClaudeMd(privDir) {
  const out = join(CLAUDE, 'CLAUDE.md');
  const base = join(KIT, 'user-config', 'CLAUDE.global.md');
  const priv = join(privDir, 'CLAUDE.md');
  const hasBase = existsSync(base);
  const hasPriv = existsSync(priv);
  if (!hasBase && !hasPriv) return;
  if (DRY_RUN) {
    console.log(`  [dry-run] compose ${out} from ${[hasBase && 'base', hasPriv && 'private'].filter(Boolean).join(' ')}`);
    return;
  }
  backup(out);
  let content = '<!-- GENERATED by claude-kit bootstrap.mjs (public base + private overlay). Edit the sources, not this file. -->\n';
  if (hasBase) content += '\n' + readFileSync(base, 'utf8');
  if (hasPriv) content += '\n' + readFileSync(priv, 'utf8');
  writeFileSync(out, content);
  console.log(`  composed ${out}`);
}

console.log(`claude-kit -> ${CLAUDE}  (from ${KIT})`);

if (LINK_TOOLING) {
  console.log('Public tooling (LINK_TOOLING=1, non-plugin install):');
  console.log('  WARNING: if the claude-kit PLUGIN is also installed, this DOUBLE-registers');
  console.log('  the same hooks/commands. Use the plugin OR LINK_TOOLING=1, never both (KIT-D013).');
  linkItems(join(KIT, 'commands'), join(CLAUDE, 'commands'), 'md');
  linkItems(join(KIT, 'agents'), join(CLAUDE, 'agents'), 'md-noreadme');
  linkItems(join(KIT, 'skills'), join(CLAUDE, 'skills'), 'dirs');
  linkItems(join(KIT, 'hooks'), join(CLAUDE, 'hooks'), 'mjs');
} else {
  console.log('Public tooling: provided by the PLUGIN (KIT-D013) — not symlinked.');
  console.log('  (Not using the plugin? Re-run with LINK_TOOLING=1 for the legacy symlink install.)');
}

link(join(KIT, 'user-config', 'statusline.sh'), join(CLAUDE, 'statusline.sh'), 'file');
try { chmodSync(join(KIT, 'user-config', 'statusline.sh'), 0o755); } catch { /* no-op on Windows */ }

const DATA = process.env.CLAUDE_DATA || '';
if (DATA && existsSync(join(DATA, 'overlay'))) {
  console.log(`Wiring overlay -> ${join(DATA, 'overlay')} (centralized)`);
  link(join(DATA, 'overlay'), join(CLAUDE, 'private'), 'junction');
}

const PRIV = process.env.CLAUDE_KIT_PRIVATE || join(CLAUDE, 'private');
if (existsSync(PRIV)) {
  console.log(`Private overlay -> ${CLAUDE}  (from ${PRIV}; private wins on name collisions)`);
  linkItems(join(PRIV, 'commands'), join(CLAUDE, 'commands'), 'md');
  linkItems(join(PRIV, 'agents'), join(CLAUDE, 'agents'), 'md-noreadme');
  linkItems(join(PRIV, 'skills'), join(CLAUDE, 'skills'), 'dirs');
  linkItems(join(PRIV, 'hooks'), join(CLAUDE, 'hooks'), 'mjs');
  if (existsSync(join(PRIV, 'statusline.sh'))) link(join(PRIV, 'statusline.sh'), join(CLAUDE, 'statusline.sh'), 'file');
  composeClaudeMd(PRIV);
  if (existsSync(join(PRIV, 'settings.private.json'))) {
    console.log(`  NOTE: merge ${join(PRIV, 'settings.private.json')} into ${join(CLAUDE, 'settings.json')} (after settings.recommended.json)`);
  }
} else {
  console.log(`No private overlay (set CLAUDE_KIT_PRIVATE, or create ${join(CLAUDE, 'private')}) — public kit only.`);
  composeClaudeMd(PRIV);
}

const capScript = join(KIT, 'scripts', 'cap.mjs');
console.log('');
if (process.platform === 'win32') {
  console.log('Add a `cap` shortcut to your PowerShell profile ($PROFILE):');
  console.log(`  function cap { node "${capScript}" @args }`);
} else {
  console.log('Add this to your shell rc (~/.zshrc on mac, ~/.bashrc on Linux):');
  console.log(`  cap(){ node "${capScript}" "$@"; }`);
}
console.log('');
if (LINK_TOOLING) {
  console.log(`Non-plugin install: merge user-config/settings.recommended.json into ${join(CLAUDE, 'settings.json')}`);
  console.log('(it enables the statusline + WIRES the hooks + pre-allows the cap/init scripts).');
} else {
  console.log('Plugin install: hooks/commands come from the plugin (no settings.json hook wiring needed).');
  console.log(`For the statusline only, enable it in ${join(CLAUDE, 'settings.json')} (see user-config/settings.recommended.json).`);
}
console.log('');
console.log(`Per project (inside the repo):  node ${join(KIT, 'scripts', 'init-project.mjs')}`);
console.log('Done.');
