#!/usr/bin/env bash
# bootstrap.sh — wire claude-kit into a machine. Idempotent and conservative:
# it ADDS to ~/.claude (symlinks commands, statusline, skills, agents, hooks) and
# never overwrites your settings.json. Run after cloning the repo.
#
#   ./bootstrap.sh                 # public kit (+ private overlay if present)
#   DRY_RUN=1 ./bootstrap.sh       # print what it would link, change nothing
#
# Private overlay (D-002): anything sensitive — personal CLAUDE.md rules,
# proprietary agents/commands/skills/hooks — lives OUTSIDE this public MIT repo,
# in a private overlay that this script composes on top. Resolution order:
#   1. $CLAUDE_KIT_PRIVATE  (a private repo clone, or any dir)
#   2. ~/.claude/private/   (gitignored)
#   3. none — public kit only
# The overlay mirrors the kit's installable layout (flat):
#   <overlay>/{commands,agents,skills,hooks}, <overlay>/statusline.sh,
#   <overlay>/CLAUDE.md, <overlay>/settings.private.json
# Overlay items are linked AFTER the public ones, so a private item of the same
# name WINS — the private layer overrides, never the reverse.
#
# On native Windows, run under WSL so all machines stay POSIX.
set -euo pipefail

KIT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLAUDE="${CLAUDE_HOME:-$HOME/.claude}"
DRY_RUN="${DRY_RUN:-0}"
mkdir -p "$CLAUDE"/{commands,agents,skills,hooks}

link() { # link <src> <dst> — back up a real file, then symlink
  local src="$1" dst="$2"
  if [ "$DRY_RUN" = "1" ]; then
    echo "  [dry-run] $dst -> $src"
    return 0
  fi
  if [ -e "$dst" ] && [ ! -L "$dst" ]; then
    mv "$dst" "$dst.bak.$(date +%s)"
    echo "  backed up existing $dst"
  fi
  ln -sfn "$src" "$dst"
  echo "  linked $dst"
}

# link_items <srcdir> <dstdir> <kind> — link a layer's items; no-op if absent.
# kind: md | md-noreadme | dirs | mjs
link_items() {
  local src="$1" dst="$2" kind="$3"
  [ -d "$src" ] || return 0
  mkdir -p "$dst"
  case "$kind" in
    md)
      for f in "$src"/*.md; do [ -e "$f" ] && link "$f" "$dst/$(basename "$f")"; done ;;
    md-noreadme)
      for f in "$src"/*.md; do
        [ -e "$f" ] || continue
        [ "$(basename "$f")" = "README.md" ] && continue
        link "$f" "$dst/$(basename "$f")"
      done ;;
    dirs)
      for d in "$src"/*/; do [ -d "$d" ] && link "${d%/}" "$dst/$(basename "$d")"; done ;;
    mjs)
      for f in "$src"/*.mjs; do [ -e "$f" ] && link "$f" "$dst/$(basename "$f")"; done ;;
  esac
}

# Compose ~/.claude/CLAUDE.md from an optional public base + optional private
# overlay. Dormant until at least one source exists, so it never clobbers a
# hand-maintained global CLAUDE.md before the rules are migrated into the kit.
compose_claude_md() {
  local out="$CLAUDE/CLAUDE.md" base="$KIT/user-config/CLAUDE.global.md" priv="$1/CLAUDE.md"
  [ -f "$base" ] || [ -f "$priv" ] || return 0
  if [ "$DRY_RUN" = "1" ]; then
    local from=""
    [ -f "$base" ] && from="$from base"
    [ -f "$priv" ] && from="$from private"
    echo "  [dry-run] compose $out from$from"
    return 0
  fi
  [ -e "$out" ] && [ ! -L "$out" ] && { mv "$out" "$out.bak.$(date +%s)"; echo "  backed up existing $out"; }
  {
    echo "<!-- GENERATED by claude-kit bootstrap.sh (public base + private overlay). Edit the sources, not this file. -->"
    [ -f "$base" ] && { echo; cat "$base"; }
    [ -f "$priv" ] && { echo; cat "$priv"; }
  } > "$out"
  echo "  composed $out"
}

echo "Public kit -> $CLAUDE  (from $KIT)"
link_items "$KIT/user-config/commands" "$CLAUDE/commands" md
link_items "$KIT/agents" "$CLAUDE/agents" md-noreadme
link_items "$KIT/skills" "$CLAUDE/skills" dirs
link_items "$KIT/hooks" "$CLAUDE/hooks" mjs
link "$KIT/user-config/statusline.sh" "$CLAUDE/statusline.sh"
chmod +x "$KIT/user-config/statusline.sh" "$KIT/scripts/"*.mjs 2>/dev/null || true

# --- claude-kit-data (private, centralized workflow data — D-008) ---
# Set CLAUDE_DATA to your claude-kit-data clone. The overlay then lives at
# $CLAUDE_DATA/overlay (one synced source), so ~/.claude/private points there. Per-project
# .ai/ is a symlink/junction into $CLAUDE_DATA/projects/<name>/, wired per repo by
# init-project.mjs from the repo's .claude-project pointer.
DATA="${CLAUDE_DATA:-}"
if [ -n "$DATA" ] && [ -d "$DATA/overlay" ]; then
  echo "Wiring overlay -> $DATA/overlay (centralized)"
  link "$DATA/overlay" "$CLAUDE/private"
fi

PRIV="${CLAUDE_KIT_PRIVATE:-$CLAUDE/private}"
if [ -d "$PRIV" ]; then
  echo "Private overlay -> $CLAUDE  (from $PRIV; private wins on name collisions)"
  link_items "$PRIV/commands" "$CLAUDE/commands" md
  link_items "$PRIV/agents" "$CLAUDE/agents" md-noreadme
  link_items "$PRIV/skills" "$CLAUDE/skills" dirs
  link_items "$PRIV/hooks" "$CLAUDE/hooks" mjs
  [ -f "$PRIV/statusline.sh" ] && link "$PRIV/statusline.sh" "$CLAUDE/statusline.sh"
  compose_claude_md "$PRIV"
  [ -f "$PRIV/settings.private.json" ] && echo "  NOTE: merge $PRIV/settings.private.json into $CLAUDE/settings.json (after settings.recommended.json)"
else
  echo "No private overlay (set CLAUDE_KIT_PRIVATE, or create $CLAUDE/private/) — public kit only."
  compose_claude_md "$PRIV"
fi

CAP_LINE="cap(){ node \"$KIT/scripts/cap.mjs\" \"\$@\"; }"
echo
echo "Add this to your shell rc (~/.zshrc on mac, ~/.bashrc on Linux/WSL):"
echo "  $CAP_LINE"
echo
echo "Then merge user-config/settings.recommended.json into $CLAUDE/settings.json"
echo "(it enables the statusline + wires the hooks + pre-allows the cap/init scripts)."
echo
echo "Per project (inside the repo):  node $KIT/scripts/init-project.mjs"
echo "  with CLAUDE_DATA set, it writes .claude-project + links .ai into"
echo "  \$CLAUDE_DATA/projects/<name>/ (centralized, D-008) rather than scaffolding in-repo."
echo "Done."
