#!/usr/bin/env node
// Regenerate the ticket reference files from the ticket markdown (DECISIONS D-006).
// Tickets are the truth; these files are GENERATED — never hand-edit them.
//   .ai/tickets/INDEX.md  — the board: every ticket (id, type, status, priority, title)
//   .ai/REGRESSIONS.md    — bug/regression chains (original -> recurrences), longest
//                           first, with the causing/fixing commits.
//
//   node scripts/index-tickets.mjs [repoRoot]   # defaults to cwd

import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { compareIds } from './id-utils.mjs';

const root = process.argv[2] || process.cwd();
const ticketsDir = join(root, '.ai', 'tickets');
const archiveDir = join(ticketsDir, 'archive');
const SKIP = new Set(['_TEMPLATE.md', 'INDEX.md']);

// Light, dependency-free read of the two config bits the ROADMAP view needs.
function readConfig() {
  let mode = 'narrative'; // safe default: never overwrite ROADMAP unless opted in
  let priorities = ['critical', 'high', 'medium', 'low'];
  try {
    const cfg = readFileSync(join(root, '.ai', 'config.yml'), 'utf8');
    const mm = cfg.match(/roadmap_mode:[ \t]*(\w+)/);
    if (mm) mode = mm[1];
    const pm = cfg.match(/priorities:[ \t]*\[([^\]]+)\]/);
    if (pm) priorities = pm[1].split(',').map((s) => s.trim());
  } catch {
    /* defaults */
  }
  return { mode, priorities };
}
const { mode: roadmapMode, priorities } = readConfig();

function field(fm, key) {
  const m = fm.match(new RegExp(`^${key}:[ \\t]*(.*)$`, 'm'));
  return m ? m[1].trim().replace(/^["']|["']$/g, '') : '';
}

function readTickets(dir, archived) {
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith('.md') && !SKIP.has(f))
    .map((f) => {
      const fm = (readFileSync(join(dir, f), 'utf8').match(/^---\n([\s\S]*?)\n---/) || [null, ''])[1];
      const id = field(fm, 'id') || (f.match(/[A-Za-z]+-\d+/) || [])[0] || f.replace(/\.md$/, '');
      return {
        id,
        archived,
        title: field(fm, 'title') || id,
        type: field(fm, 'type') || '—',
        status: field(fm, 'status') || '—',
        priority: field(fm, 'priority') || '—',
        milestone: field(fm, 'milestone'),
        regressedFrom: field(fm, 'regressed_from'),
        causingCommit: field(fm, 'causing_commit'),
        fixedCommit: field(fm, 'fixed_commit'),
      };
    });
}

const tickets = [...readTickets(ticketsDir, false), ...readTickets(archiveDir, true)];

// Fail loud on duplicate ids instead of silently last-write-wins into `byId`
// below — a collision (two files sharing an id) must never generate quietly.
const idCounts = new Map();
for (const t of tickets) idCounts.set(t.id, (idCounts.get(t.id) || 0) + 1);
const dupIds = [...idCounts.entries()].filter(([, n]) => n > 1).map(([id]) => id);
if (dupIds.length) {
  process.stderr.write(
    `index-tickets: DUPLICATE ticket id(s): ${dupIds.join(', ')}. ` +
      `Re-key one (scripts/next-id.mjs tickets) before regenerating.\n`,
  );
  process.exit(1);
}

const byId = new Map(tickets.map((t) => [t.id, t]));

// --- INDEX.md: the board ---
const HEADER = '| id | type | status | priority | title |\n| --- | --- | --- | --- | --- |';
const row = (t) => `| ${t.id} | ${t.type} | ${t.status} | ${t.priority} | ${t.title} |`;
const active = tickets.filter((t) => !t.archived);
const archived = tickets.filter((t) => t.archived);
const indexMd = [
  '<!-- GENERATED by scripts/index-tickets.mjs — do not hand-edit. Tickets are the truth. -->',
  '# Ticket board',
  '',
  `## Active (${active.length})`,
  HEADER,
  ...active.map(row),
  '',
  `## Archived (${archived.length})`,
  HEADER,
  ...archived.map(row),
  '',
].join('\n');
writeFileSync(join(ticketsDir, 'INDEX.md'), indexMd);

// --- REGRESSIONS.md: chains linked by regressed_from (linear; longest first) ---
const recurrences = tickets.filter((t) => t.regressedFrom);
const childrenOf = new Map();
for (const t of recurrences) {
  const kids = childrenOf.get(t.regressedFrom) || [];
  kids.push(t.id);
  childrenOf.set(t.regressedFrom, kids);
}
const isChild = new Set(recurrences.map((t) => t.id));
const roots = [...childrenOf.keys()].filter((id) => !isChild.has(id));

function chainFrom(rootId) {
  const out = [rootId];
  let kids = childrenOf.get(rootId) || [];
  while (kids.length) {
    out.push(kids[0]);
    kids = childrenOf.get(kids[0]) || [];
  }
  return out;
}

const commitNote = (id) => {
  const t = byId.get(id);
  const bits = [];
  if (t && t.causingCommit) bits.push(`caused by ${t.causingCommit}`);
  if (t && t.fixedCommit) bits.push(`fixed in ${t.fixedCommit}`);
  return bits.length ? ` (${bits.join('; ')})` : '';
};

const chains = roots.map(chainFrom).sort((a, b) => b.length - a.length);
const regLines = chains.length
  ? chains.map((c) => `- ${c.map((id) => `**${id}**${commitNote(id)}`).join('  →  ')}  · ${c.length} occurrence(s)`)
  : ['_No regressions linked yet._'];

const regMd = [
  '<!-- GENERATED by scripts/index-tickets.mjs — do not hand-edit. -->',
  '# Regressions',
  '',
  'Chains of `original → recurrence`, longest first (repeat offenders at the top). A',
  'recurrence is a `type: regression` ticket with `regressed_from:` set.',
  '',
  ...regLines,
  '',
].join('\n');
writeFileSync(join(root, '.ai', 'REGRESSIONS.md'), regMd);

// --- ROADMAP.md: thin sequenced index, GENERATED from ticket frontmatter ---
// Only when config roadmap_mode=generated; a narrative ROADMAP is left untouched
// (so a hand-curated one isn't clobbered before its items are ticketed).
let roadmapNote = 'ROADMAP.md left as-is (narrative mode)';
if (roadmapMode === 'generated') {
  const open = active.filter((t) => t.status !== 'done');
  const prio = (t) => {
    const i = priorities.indexOf(t.priority);
    return i < 0 ? priorities.length : i;
  };
  const bySeq = (a, b) => prio(a) - prio(b) || compareIds(a.id, b.id);
  const milestones = [...new Set(open.filter((t) => t.milestone).map((t) => t.milestone))];
  const lines = [
    '<!-- GENERATED by scripts/index-tickets.mjs — do not hand-edit. Tickets are the truth. -->',
    '# Roadmap',
    '',
  ];
  for (const m of milestones) {
    const items = open.filter((t) => t.milestone === m).sort(bySeq);
    lines.push(`## ${m}`, ...items.map((t, i) => `${i + 1}. ${t.id} — ${t.title} (${t.status})`), '');
  }
  const backlog = open.filter((t) => !t.milestone).sort(bySeq);
  if (backlog.length) {
    lines.push('## Backlog (priority order)', ...backlog.map((t) => `- ${t.id} — ${t.title} (${t.priority})`), '');
  }
  writeFileSync(join(root, '.ai', 'ROADMAP.md'), lines.join('\n'));
  roadmapNote = `ROADMAP.md generated (${milestones.length} milestone(s), ${backlog.length} backlog)`;
}

process.stdout.write(
  `Wrote .ai/tickets/INDEX.md (${active.length} active, ${archived.length} archived), .ai/REGRESSIONS.md (${chains.length} chain(s)); ${roadmapNote}.\n`,
);
