#!/usr/bin/env node
// Regenerate the ticket reference files from the ticket markdown (DECISIONS D-006).
// Tickets are the truth; these files are GENERATED — never hand-edit them.
//   .ai/tickets/INDEX.md  — the board: every ticket (id, type, status, priority, title)
//   .ai/REGRESSIONS.md    — bug/regression chains (original -> recurrences), longest
//                           first, with the causing/fixing commits.
//
//   node scripts/index-tickets.mjs [repoRoot]   # defaults to cwd

import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { compareIds } from './id-utils.mjs';
import { query } from './q.mjs';

const root = process.argv[2] || process.cwd();
const ticketsDir = join(root, '.ai', 'tickets');
const archiveDir = join(ticketsDir, 'archive');
const SKIP = new Set(['_TEMPLATE.md', 'INDEX.md']);

// Light, dependency-free read of the two config bits the ROADMAP view needs.
function readConfig() {
  let mode = 'narrative'; // safe default: never overwrite ROADMAP unless opted in
  let priorities = ['critical', 'high', 'medium', 'low'];
  try {
    const cfg = readFileSync(join(root, '.ai', 'config.yml'), 'utf8');
    const mm = cfg.match(/roadmap_mode:[ \t]*(\w+)/);
    if (mm) mode = mm[1];
    const pm = cfg.match(/priorities:[ \t]*\[([^\]]+)\]/);
    if (pm) priorities = pm[1].split(',').map((s) => s.trim());
  } catch {
    /* defaults */
  }
  return { mode, priorities };
}
const { mode: roadmapMode, priorities } = readConfig();

function field(fm, key) {
  const m = fm.match(new RegExp(`^${key}:[ \\t]*(.*)$`, 'm'));
  return m ? m[1].trim().replace(/^["']|["']$/g, '') : '';
}

function readTickets(dir, archived) {
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith('.md') && !SKIP.has(f))
    .map((f) => {
      const fm = (readFileSync(join(dir, f), 'utf8').match(/^---\n([\s\S]*?)\n---/) || [null, ''])[1];
      const id = field(fm, 'id') || (f.match(/[A-Za-z]+-\d+/) || [])[0] || f.replace(/\.md$/, '');
      return {
        id,
        archived,
        title: field(fm, 'title') || id,
        type: field(fm, 'type') || '—',
        status: field(fm, 'status') || '—',
        priority: field(fm, 'priority') || '—',
        milestone: field(fm, 'milestone'),
        regressedFrom: field(fm, 'regressed_from'),
        causingCommit: field(fm, 'causing_commit'),
        fixedCommit: field(fm, 'fixed_commit'),
        supersedes: field(fm, 'supersedes'),
        supersededBy: field(fm, 'superseded_by'),
      };
    });
}

const tickets = [...readTickets(ticketsDir, false), ...readTickets(archiveDir, true)];

// Fail loud on duplicate ids instead of silently last-write-wins — a collision (two
// files sharing an id) must never generate quietly.
const idCounts = new Map();
for (const t of tickets) idCounts.set(t.id, (idCounts.get(t.id) || 0) + 1);
const dupIds = [...idCounts.entries()].filter(([, n]) => n > 1).map(([id]) => id);
if (dupIds.length) {
  process.stderr.write(
    `index-tickets: DUPLICATE ticket id(s): ${dupIds.join(', ')}. ` +
      `Re-key one (scripts/next-id.mjs tickets) before regenerating.\n`,
  );
  process.exit(1);
}

// --- INDEX.md: the board ---
// A superseded ticket (status `superseded` OR carrying a `superseded_by` pointer) drops out of
// the ACTIVE board into its own section, so a retired duplicate never shows as live work
// (KIT-T024). Same predicate the drain's `open` query uses — one definition of "active".
const isSuperseded = (t) => t.status === 'superseded' || !!t.supersededBy;
const HEADER = '| id | type | status | priority | title |\n| --- | --- | --- | --- | --- |';
const SUP_HEADER = '| id | status | title | superseded by |\n| --- | --- | --- | --- |';
const row = (t) => `| ${t.id} | ${t.type} | ${t.status} | ${t.priority} | ${t.title} |`;
const supRow = (t) => `| ${t.id} | ${t.status} | ${t.title} | ${t.supersededBy || '—'} |`;
const active = tickets.filter((t) => !t.archived && !isSuperseded(t));
const archived = tickets.filter((t) => t.archived);
const superseded = tickets.filter((t) => !t.archived && isSuperseded(t));
const indexMd = [
  '<!-- GENERATED by scripts/index-tickets.mjs — do not hand-edit. Tickets are the truth. -->',
  '# Ticket board',
  '',
  `## Active (${active.length})`,
  HEADER,
  ...active.map(row),
  '',
  `## Superseded (${superseded.length})`,
  SUP_HEADER,
  ...superseded.map(supRow),
  '',
  `## Archived (${archived.length})`,
  HEADER,
  ...archived.map(row),
  '',
].join('\n');
writeFileSync(join(ticketsDir, 'INDEX.md'), indexMd);

// --- REGRESSIONS.md: chains linked by regressed_from (linear; longest first) ---
// Regression provenance (regressed_from + causing/fixed commits) is READ FROM THE CACHE
// via q.mjs's canned `regressions` query (KIT-T026); it fails open to the markdown the
// script already loaded, so the cache is never a hard dependency. `query` returns the
// same per-id rows from either path (cache or db-parse scan) — parity lives in q.mjs.
async function regressionData() {
  try {
    const { rows } = await query('regressions', [], { root });
    const m = new Map();
    for (const r of rows) {
      m.set(r.id, { regressedFrom: r.regressed_from || '', causingCommit: r.causing_commit || '', fixedCommit: r.fixed_commit || '' });
    }
    if (m.size) return m;
  } catch {
    /* fall through to the markdown scan the script already performed */
  }
  return new Map(tickets.map((t) => [t.id, { regressedFrom: t.regressedFrom, causingCommit: t.causingCommit, fixedCommit: t.fixedCommit }]));
}
const reg = await regressionData();

const recurrences = tickets.filter((t) => reg.get(t.id)?.regressedFrom);
const childrenOf = new Map();
for (const t of recurrences) {
  const from = reg.get(t.id).regressedFrom;
  const kids = childrenOf.get(from) || [];
  kids.push(t.id);
  childrenOf.set(from, kids);
}
const isChild = new Set(recurrences.map((t) => t.id));
const roots = [...childrenOf.keys()].filter((id) => !isChild.has(id));

function chainFrom(rootId) {
  const out = [rootId];
  let kids = childrenOf.get(rootId) || [];
  while (kids.length) {
    out.push(kids[0]);
    kids = childrenOf.get(kids[0]) || [];
  }
  return out;
}

const commitNote = (id) => {
  const r = reg.get(id);
  const bits = [];
  if (r && r.causingCommit) bits.push(`caused by ${r.causingCommit}`);
  if (r && r.fixedCommit) bits.push(`fixed in ${r.fixedCommit}`);
  return bits.length ? ` (${bits.join('; ')})` : '';
};

const chains = roots.map(chainFrom).sort((a, b) => b.length - a.length);
const regLines = chains.length
  ? chains.map((c) => `- ${c.map((id) => `**${id}**${commitNote(id)}`).join('  →  ')}  · ${c.length} occurrence(s)`)
  : ['_No regressions linked yet._'];

const regMd = [
  '<!-- GENERATED by scripts/index-tickets.mjs — do not hand-edit. -->',
  '# Regressions',
  '',
  'Chains of `original → recurrence`, longest first (repeat offenders at the top). A',
  'recurrence is a `type: regression` ticket with `regressed_from:` set.',
  '',
  ...regLines,
  '',
].join('\n');
writeFileSync(join(root, '.ai', 'REGRESSIONS.md'), regMd);

// --- SUPERSEDED.md: chains linked by supersedes (older -> newer; KIT-T024) ---
// Supersede provenance is READ FROM THE CACHE via q.mjs's `supersedes` query (KIT-T026 pattern),
// failing open to the markdown the script already loaded. An edge is newer→older (`supersedes`);
// we invert it to render the human-readable older→newer "retired by" chain, like REGRESSIONS.
async function supersedeData() {
  try {
    const { rows } = await query('supersedes', [], { root });
    if (rows.length) return new Map(rows.map((r) => [r.id, r.supersedes || '']));
  } catch {
    /* fall through to the markdown scan */
  }
  return new Map(tickets.map((t) => [t.id, t.supersedes || '']));
}
const sup = await supersedeData();
const supersedesOf = new Map([...sup].filter(([, to]) => to)); // newer -> older
const olderToNewer = new Map();
for (const [newer, older] of supersedesOf) olderToNewer.set(older, newer);
const supRoots = [...olderToNewer.keys()].filter((id) => !supersedesOf.has(id)); // never itself superseded
function supChainFrom(rootId) {
  const out = [rootId];
  let next = olderToNewer.get(rootId);
  while (next) {
    out.push(next);
    next = olderToNewer.get(next);
  }
  return out;
}
const supChains = supRoots.map(supChainFrom).sort((a, b) => b.length - a.length);
const supLines = supChains.length
  ? supChains.map((c) => `- ${c.map((id) => `**${id}**`).join('  →  ')}  · ${c.length - 1} superseded`)
  : ['_No superseded tickets yet._'];
const supMd = [
  '<!-- GENERATED by scripts/index-tickets.mjs — do not hand-edit. -->',
  '# Superseded',
  '',
  'Chains of `older → newer`, the rightmost id being the live replacement. A ticket is',
  'superseded when a newer one sets `supersedes:` (or it carries `superseded_by:` / status',
  '`superseded`); superseded tickets are dropped from the active board + drain.',
  '',
  ...supLines,
  '',
].join('\n');
writeFileSync(join(root, '.ai', 'SUPERSEDED.md'), supMd);

// --- ROADMAP.md: thin sequenced index, GENERATED from ticket frontmatter ---
// Only when config roadmap_mode=generated; a narrative ROADMAP is left untouched
// (so a hand-curated one isn't clobbered before its items are ticketed).
let roadmapNote = 'ROADMAP.md left as-is (narrative mode)';
if (roadmapMode === 'generated') {
  const open = active.filter((t) => t.status !== 'done'); // `active` already drops superseded
  const prio = (t) => {
    const i = priorities.indexOf(t.priority);
    return i < 0 ? priorities.length : i;
  };
  const bySeq = (a, b) => prio(a) - prio(b) || compareIds(a.id, b.id);
  const milestones = [...new Set(open.filter((t) => t.milestone).map((t) => t.milestone))];
  const lines = [
    '<!-- GENERATED by scripts/index-tickets.mjs — do not hand-edit. Tickets are the truth. -->',
    '# Roadmap',
    '',
  ];
  for (const m of milestones) {
    const items = open.filter((t) => t.milestone === m).sort(bySeq);
    lines.push(`## ${m}`, ...items.map((t, i) => `${i + 1}. ${t.id} — ${t.title} (${t.status})`), '');
  }
  const backlog = open.filter((t) => !t.milestone).sort(bySeq);
  if (backlog.length) {
    lines.push('## Backlog (priority order)', ...backlog.map((t) => `- ${t.id} — ${t.title} (${t.priority})`), '');
  }
  writeFileSync(join(root, '.ai', 'ROADMAP.md'), lines.join('\n'));
  roadmapNote = `ROADMAP.md generated (${milestones.length} milestone(s), ${backlog.length} backlog)`;
}

process.stdout.write(
  `Wrote .ai/tickets/INDEX.md (${active.length} active, ${superseded.length} superseded, ${archived.length} archived), ` +
    `.ai/REGRESSIONS.md (${chains.length} chain(s)), .ai/SUPERSEDED.md (${supChains.length} chain(s)); ${roadmapNote}.\n`,
);
