#!/usr/bin/env node
// Regenerate the ticket reference files from the ticket markdown (DECISIONS D-006).
// Tickets are the truth; these files are GENERATED — never hand-edit them.
//   .ai/tickets/INDEX.md  — the board: every ticket (id, type, status, priority, title)
//   .ai/REGRESSIONS.md    — bug/regression chains (original -> recurrences), longest
//                           first, with the causing/fixing commits.
//
//   node scripts/index-tickets.mjs [repoRoot]   # defaults to cwd

import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

const root = process.argv[2] || process.cwd();
const ticketsDir = join(root, '.ai', 'tickets');
const archiveDir = join(ticketsDir, 'archive');
const SKIP = new Set(['_TEMPLATE.md', 'INDEX.md']);

function field(fm, key) {
  const m = fm.match(new RegExp(`^${key}:[ \\t]*(.*)$`, 'm'));
  return m ? m[1].trim().replace(/^["']|["']$/g, '') : '';
}

function readTickets(dir, archived) {
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith('.md') && !SKIP.has(f))
    .map((f) => {
      const fm = (readFileSync(join(dir, f), 'utf8').match(/^---\n([\s\S]*?)\n---/) || [null, ''])[1];
      const id = field(fm, 'id') || (f.match(/[A-Za-z]+-\d+/) || [])[0] || f.replace(/\.md$/, '');
      return {
        id,
        archived,
        title: field(fm, 'title') || id,
        type: field(fm, 'type') || '—',
        status: field(fm, 'status') || '—',
        priority: field(fm, 'priority') || '—',
        regressedFrom: field(fm, 'regressed_from'),
        causingCommit: field(fm, 'causing_commit'),
        fixedCommit: field(fm, 'fixed_commit'),
      };
    });
}

const tickets = [...readTickets(ticketsDir, false), ...readTickets(archiveDir, true)];
const byId = new Map(tickets.map((t) => [t.id, t]));

// --- INDEX.md: the board ---
const HEADER = '| id | type | status | priority | title |\n| --- | --- | --- | --- | --- |';
const row = (t) => `| ${t.id} | ${t.type} | ${t.status} | ${t.priority} | ${t.title} |`;
const active = tickets.filter((t) => !t.archived);
const archived = tickets.filter((t) => t.archived);
const indexMd = [
  '<!-- GENERATED by scripts/index-tickets.mjs — do not hand-edit. Tickets are the truth. -->',
  '# Ticket board',
  '',
  `## Active (${active.length})`,
  HEADER,
  ...active.map(row),
  '',
  `## Archived (${archived.length})`,
  HEADER,
  ...archived.map(row),
  '',
].join('\n');
writeFileSync(join(ticketsDir, 'INDEX.md'), indexMd);

// --- REGRESSIONS.md: chains linked by regressed_from (linear; longest first) ---
const recurrences = tickets.filter((t) => t.regressedFrom);
const childrenOf = new Map();
for (const t of recurrences) {
  const kids = childrenOf.get(t.regressedFrom) || [];
  kids.push(t.id);
  childrenOf.set(t.regressedFrom, kids);
}
const isChild = new Set(recurrences.map((t) => t.id));
const roots = [...childrenOf.keys()].filter((id) => !isChild.has(id));

function chainFrom(rootId) {
  const out = [rootId];
  let kids = childrenOf.get(rootId) || [];
  while (kids.length) {
    out.push(kids[0]);
    kids = childrenOf.get(kids[0]) || [];
  }
  return out;
}

const commitNote = (id) => {
  const t = byId.get(id);
  const bits = [];
  if (t && t.causingCommit) bits.push(`caused by ${t.causingCommit}`);
  if (t && t.fixedCommit) bits.push(`fixed in ${t.fixedCommit}`);
  return bits.length ? ` (${bits.join('; ')})` : '';
};

const chains = roots.map(chainFrom).sort((a, b) => b.length - a.length);
const regLines = chains.length
  ? chains.map((c) => `- ${c.map((id) => `**${id}**${commitNote(id)}`).join('  →  ')}  · ${c.length} occurrence(s)`)
  : ['_No regressions linked yet._'];

const regMd = [
  '<!-- GENERATED by scripts/index-tickets.mjs — do not hand-edit. -->',
  '# Regressions',
  '',
  'Chains of `original → recurrence`, longest first (repeat offenders at the top). A',
  'recurrence is a `type: regression` ticket with `regressed_from:` set.',
  '',
  ...regLines,
  '',
].join('\n');
writeFileSync(join(root, '.ai', 'REGRESSIONS.md'), regMd);

process.stdout.write(
  `Wrote .ai/tickets/INDEX.md (${active.length} active, ${archived.length} archived) and .ai/REGRESSIONS.md (${chains.length} chain(s)).\n`,
);
